### ISSUE TITLE
Could you upload your paper in the git repository first ?

### ISSUE THREAD

**Issue by bitallin** [benbijituo/SpellBERT#2]

**Comment by benbijituo** [comment]
Sorry. We plan to release our code in December.

**Comment by noletter** [comment]
the paper, not code.

**Comment by noletter** [comment]
> Sorry. We plan to release our code in December.

the paper, not code.

**Comment by Arvid-pku** [comment]
> > Sorry. We plan to release our code in December.
> 
> the paper, not code.
You can find the paper from https://aclanthology.org/2021.emnlp-main.287.pdf
But now it is 12.29, December is disappearing（doge

**Comment by datalee** [comment]
> December

December？
